// The Vault linter. It reads files and nothing else: no writes, no bridge calls.
// Every rule states a folder convention. A Note is any markdown file in the Vault, a link
// is a prose line carrying a wikilink, and an outline is the markdown Enso generates for a
// Canvas under `Canvases/`. Graph JSON is a layout command input, not a Vault file.

import { readFileSync, readdirSync, statSync } from "node:fs";
import { extname, join, relative, sep } from "node:path";
import { compareStrings } from "./canvas-spec.js";
import { EnsoCliError } from "./errors.js";
import { FrontmatterError, hasFrontmatterFence, parseFrontmatter } from "./frontmatter.js";

export const MANIFEST_SUFFIX = ".canvas.md";
/// The first line of every outline Enso writes. Matches `CanvasOutline.headerPrefix` in the app.
export const OUTLINE_HEADER_PREFIX = "<!-- Canvas outline generated by Enso from Canvas ";

export type CheckFinding = {
  code: string;
  file: string;
  message: string;
  details?: Record<string, unknown>;
};

export type CheckReport = {
  root: string;
  checked: { notes: number; outlines: number };
  violations: CheckFinding[];
  warnings: CheckFinding[];
};

type Prose = { body: string; bodyOffset: number };

type NoteFile = Prose & {
  file: string;
  title: string;
  generated: boolean;
};

export function checkEnsoFolder(root: string): CheckReport {
  // Wikilinks resolve across the folder, so one file cannot be linted alone.
  if (statSync(root, { throwIfNoEntry: false })?.isFile()) {
    throw new Error(`enso check takes the Vault folder, not a file. Run it on the folder that holds ${root}.`);
  }
  const violations: CheckFinding[] = [];
  const notes: NoteFile[] = [];

  for (const path of markdownFiles(root)) {
    const file = relative(root, path).split(sep).join("/");
    if (file.endsWith(MANIFEST_SUFFIX)) continue;
    const source = readFileSync(path, "utf8");
    const read = readNote(file, source);
    if (read.note) notes.push(read.note);
    violations.push(...read.violations);
  }

  const byTitle = new Map<string, NoteFile[]>();
  for (const note of notes) byTitle.set(note.title, [...(byTitle.get(note.title) ?? []), note]);

  violations.push(...duplicateTitles(byTitle));
  violations.push(...unresolvedWikilinks(notes, byTitle));

  const outlines = notes.filter((note) => note.generated).length;
  return {
    root,
    checked: { notes: notes.length - outlines, outlines },
    violations,
    warnings: []
  };
}

function markdownFiles(root: string): string[] {
  const files: string[] = [];
  for (const entry of [...readEntries(root)].sort((a, b) => compareStrings(a.name, b.name))) {
    if (entry.name.startsWith(".")) continue;
    const path = join(root, entry.name);
    if (entry.isDirectory()) {
      files.push(...markdownFiles(path));
      continue;
    }
    if (entry.isSymbolicLink() && !isFile(path)) continue;
    if (extname(entry.name).toLowerCase() === ".md") files.push(path);
  }
  return files;
}

function readEntries(root: string) {
  try {
    return readdirSync(root, { withFileTypes: true });
  } catch (error) {
    throw new EnsoCliError("invalid_input", `Folder '${root}' cannot be read: ${error instanceof Error ? error.message : "unknown error"}`, {
      path: "folder",
      expected: "a readable folder of authoring files",
      hint: "check lints files on disk; it does not inspect live canvases. After layout --apply, verify with `enso context --vision` instead."
    });
  }
}

function isFile(path: string): boolean {
  try {
    return statSync(path).isFile();
  } catch {
    return false;
  }
}

// A Note's title is its filename stem, the same identity layout resolves members by.
// Identity lives in the app's index, never in the file, so frontmatter is whatever the author
// wrote and only has to parse.
function readNote(file: string, source: string): { note?: NoteFile; violations: CheckFinding[] } {
  const title = file.slice(file.lastIndexOf("/") + 1).replace(/\.md$/i, "");
  const generated = source.startsWith(OUTLINE_HEADER_PREFIX);
  if (!hasFrontmatterFence(source)) {
    return { note: { file, title, generated, body: source.replace(/\r\n/g, "\n"), bodyOffset: 0 }, violations: [] };
  }
  let frontmatter: ReturnType<typeof parseFrontmatter>;
  try {
    frontmatter = parseFrontmatter(source);
  } catch (error) {
    return { violations: [findingFromError("frontmatter_invalid", file, error, "Note frontmatter is invalid")] };
  }
  const { value, body, bodyOffset } = frontmatter;
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return {
      violations: [{ code: "frontmatter_invalid", file, message: "Note frontmatter must be a `key: value` mapping", details: { path: "frontmatter" } }]
    };
  }
  return { note: { file, title, generated, body, bodyOffset }, violations: [] };
}

function findingFromError(code: string, file: string, error: unknown, fallback: string): CheckFinding {
  const body = error instanceof EnsoCliError ? error.body : undefined;
  const line = error instanceof FrontmatterError ? error.line : typeof body?.details?.line === "number" ? body.details.line : undefined;
  const path = typeof body?.details?.path === "string" ? body.details.path : "frontmatter";
  return {
    code,
    file,
    message: error instanceof Error ? error.message : fallback,
    details: { path, ...(line === undefined ? {} : { line }) }
  };
}

// Wikilinks and canvas members resolve by title, so two files sharing one is a broken
// reference rather than a tie to break.
function duplicateTitles(byTitle: Map<string, NoteFile[]>): CheckFinding[] {
  const findings: CheckFinding[] = [];
  for (const [title, group] of byTitle) {
    if (group.length < 2) continue;
    const files = group.map((note) => note.file).sort(compareStrings);
    for (const file of files) {
      findings.push({
        code: "duplicate_title",
        file,
        message: `Title '${title}' is claimed by ${files.join(", ")}`,
        details: { title, files }
      });
    }
  }
  return findings;
}

const WIKILINK_PATTERN = /\[\[([^\]]+)\]\]/g;

function unresolvedWikilinks(files: Array<Prose & { file: string; generated?: boolean }>, byTitle: Map<string, NoteFile[]>): CheckFinding[] {
  const findings: CheckFinding[] = [];
  for (const source of files) {
    if (source.generated) continue;
    let fenced = false;
    source.body.split("\n").forEach((text, index) => {
      if (/^\s*(```|~~~)/.test(text)) {
        fenced = !fenced;
        return;
      }
      if (fenced) return;
      // A code span shows the syntax. `[[Target]]` in backticks is not a wikilink.
      const prose = text.replace(/`[^`]*`/g, (span) => " ".repeat(span.length));
      for (const match of prose.matchAll(WIKILINK_PATTERN)) {
        const target = wikilinkTarget(match[1]);
        if (target === "" || byTitle.has(target)) continue;
        findings.push({
          code: "unresolved_wikilink",
          file: source.file,
          message: `Wikilink [[${target}]] resolves to no Note in the folder`,
          details: { target, line: source.bodyOffset + index + 1 }
        });
      }
    });
  }
  return findings;
}

function wikilinkTarget(raw: string): string {
  return raw.split("|")[0].split("#")[0].trim();
}
